### ISSUE TITLE
Problem with email verification.

### ISSUE THREAD

**Issue by techlover9922** [techlover9922/React-ui#1]
My project is using Next.
There is a Register/Login page.
I want to add email verification functionality when user registers on our system.
If you have experience of that especially for next, help me.

**Comment by 486xtm** [comment]
Hi @techlover9922 .
follow these steps and you will get success.

Prepare your google app password.
Download nodemailor module
Code like this.
const nodemailer = require('nodemailer');

// Create a transporter object using the default SMTP transport
let transporter = nodemailer.createTransport({
  service: 'gmail', // Use a service like Gmail. You can also use other SMTP services.
  auth: {
    user: 'your-email@gmail.com', // Your email
    pass: 'your-email-password',  // Your email password or app-specific password
  },
});

// Set up email data
let mailOptions = {
  from: '"Your Name" <your-email@gmail.com>', // Sender address
  to: 'recipient-email@example.com',          // List of recipients
  subject: 'Hello from Node.js',              // Subject line
  text: 'Hello world?',                       // Plain text body
  html: '<b>Hello world?</b>',                // HTML body
};

// Send mail with defined transport object
transporter.sendMail(mailOptions, (error, info) => {
  if (error) {
    return console.log(error);
  }
  console.log('Message sent: %s', info.messageId);
  console.log('Preview URL: %s', nodemailer.getTestMessageUrl(info));
});

**Comment by techlover9922** [comment]
Thank.
But how can I get app password?

**Comment by 486xtm** [comment]
Create App password at google settings.
https://support.google.com/mail/thread/205453566/how-to-generate-an-app-password?hl=en

**Comment by techlover9922** [comment]
Great job.

**Comment by techlover9922** [comment]
> Hi @techlover9922 . follow these steps and you will get success.
> 
> Prepare your google app password. Download nodemailor module Code like this. const nodemailer = require('nodemailer');
> 
> // Create a transporter object using the default SMTP transport let transporter = nodemailer.createTransport({ service: 'gmail', // Use a service like Gmail. You can also use other SMTP services. auth: { user: '[your-email@gmail.com](mailto:your-email@gmail.com)', // Your email pass: 'your-email-password', // Your email password or app-specific password }, });
> 
> // Set up email data let mailOptions = { from: '"Your Name" [your-email@gmail.com](mailto:your-email@gmail.com)', // Sender address to: '[recipient-email@example.com](mailto:recipient-email@example.com)', // List of recipients subject: 'Hello from Node.js', // Subject line text: 'Hello world?', // Plain text body html: 'Hello world?', // HTML body };
> 
> // Send mail with defined transport object transporter.sendMail(mailOptions, (error, info) => { if (error) { return console.log(error); } console.log('Message sent: %s', info.messageId); console.log('Preview URL: %s', nodemailer.getTestMessageUrl(info)); });

Thanks @486xtm. I agree with this suggestion. Refactoring the code will make it easier to maintain and understand.

**Comment by techlover9922** [comment]
> > Hi @techlover9922 . follow these steps and you will get success.
> > Prepare your google app password. Download nodemailor module Code like this. const nodemailer = require('nodemailer');
> > // Create a transporter object using the default SMTP transport let transporter = nodemailer.createTransport({ service: 'gmail', // Use a service like Gmail. You can also use other SMTP services. auth: { user: '[your-email@gmail.com](mailto:your-email@gmail.com)', // Your email pass: 'your-email-password', // Your email password or app-specific password }, });
> > // Set up email data let mailOptions = { from: '"Your Name" [your-email@gmail.com](mailto:your-email@gmail.com)', // Sender address to: '[recipient-email@example.com](mailto:recipient-email@example.com)', // List of recipients subject: 'Hello from Node.js', // Subject line text: 'Hello world?', // Plain text body html: 'Hello world?', // HTML body };
> > // Send mail with defined transport object transporter.sendMail(mailOptions, (error, info) => { if (error) { return console.log(error); } console.log('Message sent: %s', info.messageId); console.log('Preview URL: %s', nodemailer.getTestMessageUrl(info)); });
> 
> Thanks @486xtm. I agree with this suggestion. Refactoring the code will make it easier to maintain and understand.
But how can I get app password?

**Comment by 486xtm** [comment]
> > > Hi @techlover9922 . follow these steps and you will get success.
> > > Prepare your google app password. Download nodemailor module Code like this. const nodemailer = require('nodemailer');
> > > // Create a transporter object using the default SMTP transport let transporter = nodemailer.createTransport({ service: 'gmail', // Use a service like Gmail. You can also use other SMTP services. auth: { user: '[your-email@gmail.com](mailto:your-email@gmail.com)', // Your email pass: 'your-email-password', // Your email password or app-specific password }, });
> > > // Set up email data let mailOptions = { from: '"Your Name" [your-email@gmail.com](mailto:your-email@gmail.com)', // Sender address to: '[recipient-email@example.com](mailto:recipient-email@example.com)', // List of recipients subject: 'Hello from Node.js', // Subject line text: 'Hello world?', // Plain text body html: 'Hello world?', // HTML body };
> > > // Send mail with defined transport object transporter.sendMail(mailOptions, (error, info) => { if (error) { return console.log(error); } console.log('Message sent: %s', info.messageId); console.log('Preview URL: %s', nodemailer.getTestMessageUrl(info)); });
> > 
> > 
> > Thanks @486xtm. I agree with this suggestion. Refactoring the code will make it easier to maintain and understand.
> > But how can I get app password?

Create App password at google settings.
https://support.google.com/mail/thread/205453566/how-to-generate-an-app-password?hl=en

**Comment by techlover9922** [comment]
> > > > Hi @techlover9922 . follow these steps and you will get success.
> > > > Prepare your google app password. Download nodemailor module Code like this. const nodemailer = require('nodemailer');
> > > > // Create a transporter object using the default SMTP transport let transporter = nodemailer.createTransport({ service: 'gmail', // Use a service like Gmail. You can also use other SMTP services. auth: { user: '[your-email@gmail.com](mailto:your-email@gmail.com)', // Your email pass: 'your-email-password', // Your email password or app-specific password }, });
> > > > // Set up email data let mailOptions = { from: '"Your Name" [your-email@gmail.com](mailto:your-email@gmail.com)', // Sender address to: '[recipient-email@example.com](mailto:recipient-email@example.com)', // List of recipients subject: 'Hello from Node.js', // Subject line text: 'Hello world?', // Plain text body html: 'Hello world?', // HTML body };
> > > > // Send mail with defined transport object transporter.sendMail(mailOptions, (error, info) => { if (error) { return console.log(error); } console.log('Message sent: %s', info.messageId); console.log('Preview URL: %s', nodemailer.getTestMessageUrl(info)); });
> > > 
> > > 
> > > Thanks @486xtm. I agree with this suggestion. Refactoring the code will make it easier to maintain and understand.
> > > But how can I get app password?
> 
> Create App password at google settings. https://support.google.com/mail/thread/205453566/how-to-generate-an-app-password?hl=en

Great job.
